DATA:
  path: "/Users/gear8675/Documents/linkedin-parser/linkedin_parser/data/test4"

BROWSER:
  proxy: "216.56.48.118:9000"
  chrome_options:
    - "--disable-infobars"
    - "user-agent=google"

LINKEDIN:
  email: "alexey79smith@gmail.com"
  password: "Boss8675"
