DATA:
  path: "/Users/gear8675/Documents/linkedin-parser/linkedin_parser/data/test4"

BROWSER:
  proxy: "999.99.99.999:9000"
  chrome_options:
    - "--disable-infobars"
    - "user-agent=google"

LINKEDIN:
  email: "test@gmail.com"
  password: "test123"
